language: python
sudo: false
python:
- '3.6'
install:
- travis_retry pip install -r requirements.txt
script:
- python travis.py
branches:
  only:
  - master
env:
  #matrix:
  global:
  - secure: rrZHyWBxSterIWdcutq3gmzkCu4ntmUrYS2/T81utOfEcqrtobm7KmjhXG1zeoqGTZFbJxeYJif8YcXynaQ0bLCvCHHfhuxG/5Q6KF/E4a2Pud6qHFsLaMEgXSpgwovEkiA+vsNgL3hZDBXnlOCVJF9DOPGshlqxFxVgeSZDJJBD+XdUYp9UCstIRnjA8lGZq78+rMaSEbY78Un/qs/JGpYKYb5J/sF4sXu5YS4IvuiA1aq6cI5RmzqAP7iBnJPi+jbZqj/zPhTP7Sz4JupF3FIja/cuoS4zv8j/L5nXmbivyXSUYBY8mC4nge93Gu+GhTNNRrUk/gfjpkyLUcodKbfnO74IFvaE9rtsWiNUhu+vJsZ7f9E44VmUZ3f/LcwOPQIDxbM0e6SoqJBkwtOntpeivYkvoWZhelrd1EV6v1GtrHz7cw4C857mCx52teFmdLXQCgmKPHpkxQu2rPUqWm0dYhKDwav+zY2rgmaCKzSfvymJQSiLhk7hgwO1zsTNrXBMFov4kDsbYHIya+9wCXcfDmsNVYparBD91NIVyRC7IGbz09lCaYozkt/zbaVCSTOg5sKzvLd5b6GRdPCWFjuKutPabBpqlOGFh6gG3/0CKcfOXxlxI8kYFDKmbrrN7H8r8+T7PHsnN05VmORY4Jodk1/Kep6G4EFlRIOY3QI=
  - secure: igroUArZGxXyy6pLd2oTyOx/TNN2OqQyfKBvibqSopt5XAHxEFOrHPPZZMbyW5hvjfZuWLqMbRGOxanQEIC/Orqq+vTv4Ys7iDFFn2TKPRW6mf2RVu7UKA3vz1C4itOgTYMJoJ83s9D3iy4ACee9RNsM5l2s9UUf30FgKgbxvMzPquo+v7KjNGytrf5IYoLsXWxkykDBqTRs/jRdVlV0LVWNKyAfp+jk6M8YNjDUVMAvsLy1h1nJUbUVoO0okGX2ktZV8+bUgr/JANivd4Jde0Wuqstu5/goMIbt8Wbpt1uGz2JwqycKaqc1YTi3tAKfJgTmPzmz9oQAj1/Pt4UHzaoQayINA8ymsuHmVpEd6GDLNREU8Vfinl/4zQGPpoHdk6V2LLo6YCus0hIROKBnwXC6m6Vso8cgJTrBGS1HiTrZ5qi6fgWsectLgjRcBSCBpoCeEosbQ+OyTmg2n/HwrHsVxoKBN9Knl6QtYSRp0SVu/78l3wUc6VOqS6K7/PE3GDIDim89xxJIZHLZxBhQUaPBeLKkQpFB0n0/9+EcRs6DVg2sG9k+sX4zSEknm3OzJE+tBdmaOpoV6bdkkxu0+AzCZkWJVcnyRkeBPKvR9HcZihZ/hBEg51quM20Z8KUf6TQCDUCzdTj17IockDc7lkExSLi7Fo6XoQUcCB/iRqw=
