language: python
sudo: false
python:
- '3.6'
install:
- travis_retry pip install -r requirements.txt
script:
- python travis.py
branches:
  only:
  - master
env:
  #matrix:
  global:
  secure: "OKYizkYrLbb8Hs6Na5Y+izC4vOf3S93xwfX8TTl6wvglJERYGIkbLolw1grs12V6VORFe03CMxLIYHBylxilDWnz1DxKM/nCkIfudeoYUrLNZCCyoAs9WIM0ZUunLiA3XSOizXkfcE6DziQhCcRGK6XsNHhQ42EwNfZwPuzrtQB2lct3DcNCOcH1hsE9efsdxDqKX0fo6RB+tHeAmJ2+L9r5O8++lqTI3Wo81utYcSkqGks+KguYOYuJnSMDbUaVYLB16SZnXNGMOrGaJeYfBzxn0ISD6LpOVFLTktu39JaMxjB33mK1wy7/OszIjm6QKq0gMO79cXokXrC6unC2117pkVE6AxufSf6a9UGjBCnBdJ4stTQxL+D26xmVv78b9kIg1fxFlVxySiKbOOS0RBaiJ0Cf0GUCUIvkTNukgVP2NXvpH+SimisJH2/4iAn4cpP2R8hdb9F49NyRcy1g6d6WFceEvXP/Vqe3aJBfyMob7Gh8dSWw6LpTLj47W9g+VbO21v8j1XAngqRUgdmcFZoRRwymfYYTHV6jZnmvpmVdmQRobXj7DVN/Hdf7y2lf4q5fa6onwkXYhgSLacs9Z3kEXbVsWn914BVKDaAkI0lTXxAj3sqkaW3/BRsTvCful+j9ROcix633uyNnVdK2KSTZlomRwJ+YrnrYaWA5HBU="
  - secure: "igroUArZGxXyy6pLd2oTyOx/TNN2OqQyfKBvibqSopt5XAHxEFOrHPPZZMbyW5hvjfZuWLqMbRGOxanQEIC/Orqq+vTv4Ys7iDFFn2TKPRW6mf2RVu7UKA3vz1C4itOgTYMJoJ83s9D3iy4ACee9RNsM5l2s9UUf30FgKgbxvMzPquo+v7KjNGytrf5IYoLsXWxkykDBqTRs/jRdVlV0LVWNKyAfp+jk6M8YNjDUVMAvsLy1h1nJUbUVoO0okGX2ktZV8+bUgr/JANivd4Jde0Wuqstu5/goMIbt8Wbpt1uGz2JwqycKaqc1YTi3tAKfJgTmPzmz9oQAj1/Pt4UHzaoQayINA8ymsuHmVpEd6GDLNREU8Vfinl/4zQGPpoHdk6V2LLo6YCus0hIROKBnwXC6m6Vso8cgJTrBGS1HiTrZ5qi6fgWsectLgjRcBSCBpoCeEosbQ+OyTmg2n/HwrHsVxoKBN9Knl6QtYSRp0SVu/78l3wUc6VOqS6K7/PE3GDIDim89xxJIZHLZxBhQUaPBeLKkQpFB0n0/9+EcRs6DVg2sG9k+sX4zSEknm3OzJE+tBdmaOpoV6bdkkxu0+AzCZkWJVcnyRkeBPKvR9HcZihZ/hBEg51quM20Z8KUf6TQCDUCzdTj17IockDc7lkExSLi7Fo6XoQUcCB/iRqw="
